version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "security: "
    reviewers:
      - "MrShark"
    groups:
      production-dependencies:
        applies-to: security-updates
        dependency-type: "production"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    commit-message:
      prefix: "chore: "
    reviewers:
      - "MrShark"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "chore: "
    reviewers:
      - "MrShark"
