"""Lists of occupations for Classic and Modern settings."""

occupations_base = {
    "Accountant": {
        "skill_points": "EDU×4",
        "credit_range": (30, 70),
        "skills": (
            "Accounting",
            "Law",
            "Library Use",
            "Listen",
            "Persuade",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Acrobat": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (9, 20),
        "skills": (
            "Climb",
            "Dodge",
            "Jump",
            "Throw",
            "Spot Hidden",
            "Swim",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Stage Actor": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (9, 40),
        "skills": (
            "Art and Craft (Acting)",
            "Disguise",
            "FIGHT",
            "History",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "RANDOM",
        ),
    },
    "Film Actor": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (20, 90),
        "skills": (
            "Art and Craft (Acting)",
            "Disguise",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "RANDOM",
            "RANDOM",
            "Drive Auto",
        ),
    },
    "Agency Detective": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (20, 45),
        "skills": (
            "SOCIAL",
            "Fighting (Brawl)",
            "FIREARM",
            "Law",
            "Library Use",
            "Psychology",
            "Stealth",
            "Track",
        ),
    },
    "Animal Trainer": {
        "skill_points": "EDU×2+APP×2|EDU×2+POW×2",
        "credit_range": (10, 40),
        "skills": (
            "Animal Handling",
            "Jump",
            "Listen",
            "Natural World",
            "Science (Zoology)",
            "Stealth",
            "Track",
            "RANDOM",
        ),
    },
    "Antiquarian": {
        "skill_points": "EDU×4",
        "credit_range": (30, 70),
        "skills": (
            "Appraise",
            "History",
            "Library Use",
            "Spot Hidden",
            "ART",
            "Language (Other)",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Antique Dealer": {
        "skill_points": "EDU×4",
        "credit_range": (30, 50),
        "skills": (
            "Accounting",
            "Appraise",
            "Drive Auto",
            "SOCIAL",
            "SOCIAL",
            "History",
            "Library Use",
            "Navigate",
        ),
    },
    "Archaeologist": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Appraise",
            "Archaeology",
            "History",
            "Language (Other)",
            "Library Use",
            "Spot Hidden",
            "Mechanical Repair",
            "Navigate",
            "SCIENCE",
            "RANDOM",
        ),
    },
    "Artist": {
        "skill_points": "EDU×2+POW×2|EDU×2+DEX×2",
        "credit_range": (9, 50),
        "skills": (
            "ART",
            "History",
            "Natural World",
            "SOCIAL",
            "Language (Other)",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Assassin": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (30, 60),
        "skills": (
            "Disguise",
            "Electrical Repair",
            "FIGHT",
            "FIREARM",
            "Locksmith",
            "Mechanical Repair",
            "Stealth",
            "Psychology",
        ),
    },
    "Asylum Attendant": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (8, 20),
        "skills": (
            "Dodge",
            "Fighting (Brawl)",
            "First Aid",
            "SOCIAL",
            "SOCIAL",
            "Listen",
            "Psychology",
            "Stealth",
        ),
    },
    "Athlete": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Climb",
            "Jump",
            "Fighting (Brawl)",
            "Ride",
            "Swim",
            "Throw",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Author": {
        "skill_points": "EDU×4",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Literature)",
            "Language (Own)",
            "Psychology",
            "Library Use",
            "History",
            "Occult",
            "Natural World",
            "Language (Other)",
            "RANDOM",
        ),
    },
    "Bank Robber": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (5, 75),
        "skills": (
            "Drive Auto",
            "Electrical Repair",
            "Mechanical Repair",
            "FIGHT",
            "FIREARM",
            "Intimidate",
            "Locksmith",
            "Operate Heavy Machinery",
            "RANDOM",
        ),
    },
    "Bartender": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (8, 25),
        "skills": (
            "Accounting",
            "SOCIAL",
            "SOCIAL",
            "Fighting (Brawl)",
            "Listen",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Big Game Hunter": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (20, 50),
        "skills": (
            "FIREARM",
            "Listen",
            "Spot Hidden",
            "Natural World",
            "Navigate",
            "Language (Other)",
            "SURVIVE",
            "Science (Biology)",
            "Science (Botany)",
            "Science (Zoology)",
            "Stealth",
            "Track",
        ),
    },
    "Book Dealer": {
        "skill_points": "EDU×4",
        "credit_range": (20, 40),
        "skills": (
            "Accounting",
            "Appraise",
            "Drive Auto",
            "History",
            "Library Use",
            "Language (Own)",
            "Language (Other)",
            "SOCIAL",
        ),
    },
    "Bootlegger": {
        "skill_points": "EDU×2+STR×2",
        "credit_range": (5, 30),
        "skills": (
            "Drive Auto",
            "FIGHT",
            "FIREARM",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "Stealth",
            "Spot Hidden",
        ),
    },
    "Bounty Hunter": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Drive Auto",
            "Electrical Repair",
            "FIGHT",
            "FIREARM",
            "SOCIAL",
            "Law",
            "Psychology",
            "Track",
            "Stealth",
        ),
    },
    "Boxer/Wrestler": {
        "skill_points": "EDU×2+STR×2",
        "credit_range": (9, 60),
        "skills": (
            "RANDOM",
            "RANDOM",
            "Dodge",
            "Fighting (Brawl)",
            "Intimidate",
            "Jump",
            "Psychology",
            "Spot Hidden",
        ),
    },
    "Burglar": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (5, 40),
        "skills": (
            "Appraise",
            "Climb",
            "Electrical Repair",
            "Mechanical Repair",
            "Listen",
            "Locksmith",
            "Sleight of Hand",
            "Stealth",
            "Spot Hidden",
        ),
    },
    "Butler/Valet/Maid": {
        "skill_points": "EDU×4",
        "credit_range": (9, 40),
        "skills": (
            "Accounting",
            "Appraise",
            "ART",
            "First Aid",
            "Listen",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Chauffeur": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (10, 40),
        "skills": (
            "Drive Auto",
            "SOCIAL",
            "SOCIAL",
            "Listen",
            "Mechanical Repair",
            "Navigate",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Clergy": {
        "skill_points": "EDU×4",
        "credit_range": (9, 60),
        "skills": (
            "Accounting",
            "History",
            "Library Use",
            "Listen",
            "Psychology",
            "SOCIAL",
            "Language (Other)",
            "RANDOM",
        ),
    },
    "Conman": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (10, 65),
        "skills": (
            "Appraise",
            "Art and Craft (Acting)",
            "Law",
            "Language (Other)",
            "Listen",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "Sleight of Hand",
        ),
    },
    "Cowboy/girl": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 20),
        "skills": (
            "Dodge",
            "FIGHT",
            "FIREARM",
            "First Aid",
            "Natural World",
            "Jump",
            "Ride",
            "SURVIVE",
            "Throw",
            "Track",
        ),
    },
    "Craftsperson": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (10, 40),
        "skills": (
            "Accounting",
            "ART",
            "ART",
            "Mechanical Repair",
            "Natural World",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Criminal": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (5, 65),
        "skills": (
            "Art and Craft (Acting)",
            "Disguise",
            "Appraise",
            "SOCIAL",
            "FIGHT",
            "FIREARM",
            "Locksmith",
            "Mechanical Repair",
            "Stealth",
            "Psychology",
            "Spot Hidden",
        ),
    },
    "Cult Leader": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (30, 60),
        "skills": (
            "Accounting",
            "SOCIAL",
            "SOCIAL",
            "Occult",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Dilettante": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (50, 99),
        "skills": (
            "Ride",
            "FIREARM",
            "ART",
            "SOCIAL",
            "Language (Other)",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Diver": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (9, 30),
        "skills": (
            "Diving",
            "First Aid",
            "Mechanical Repair",
            "Pilot (Boat)",
            "Science (Biology)",
            "Spot Hidden",
            "Swim",
            "RANDOM",
        ),
    },
    "Doctor Of Medicine": {
        "skill_points": "EDU×4",
        "credit_range": (30, 80),
        "skills": (
            "First Aid",
            "Language (Latin)",
            "Medicine",
            "Psychology",
            "Science (Biology)",
            "Science (Pharmacy)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Drifter": {
        "skill_points": "EDU×2+APP×2|EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (0, 5),
        "skills": (
            "Climb",
            "Jump",
            "Navigate",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Driver": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 20),
        "skills": (
            "Drive Auto",
            "SOCIAL",
            "SOCIAL",
            "Listen",
            "Mechanical Repair",
            "Navigate",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Editor": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Accounting",
            "History",
            "Language (Own)",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Elected Official": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (50, 90),
        "skills": (
            "Charm",
            "History",
            "Intimidate",
            "Fast Talk",
            "Listen",
            "Language (Own)",
            "Persuade",
            "Psychology",
        ),
    },
    "Engineer": {
        "skill_points": "EDU×4",
        "credit_range": (30, 60),
        "skills": (
            "Art and Craft (Technical Drawing)",
            "Electrical Repair",
            "Library Use",
            "Mechanical Repair",
            "Operate Heavy Machinery",
            "Science (Engineering)",
            "Science (Physics)",
            "RANDOM",
        ),
    },
    "Entertainer": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Acting)",
            "Art and Craft (Singing)",
            "Disguise",
            "Listen",
            "Psychology",
            "SOCIAL",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Farmer": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Farming)",
            "Drive Auto",
            "SOCIAL",
            "Mechanical Repair",
            "Natural World",
            "Operate Heavy Machinery",
            "Track",
            "RANDOM",
        ),
    },
    "Federal Agent": {
        "skill_points": "EDU×4",
        "credit_range": (20, 40),
        "skills": (
            "Drive Auto",
            "Fighting (Brawl)",
            "FIREARM",
            "Law",
            "Persuade",
            "Stealth",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Fence": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (20, 40),
        "skills": (
            "Accounting",
            "Appraise",
            "Art and Craft (Forgery)",
            "History",
            "SOCIAL",
            "Library Use",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Firefighter": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Climb",
            "Dodge",
            "Drive Auto",
            "First Aid",
            "Jump",
            "Mechanical Repair",
            "Operate Heavy Machinery",
            "Throw",
        ),
    },
    "Foreign Correspondent": {
        "skill_points": "EDU×4",
        "credit_range": (10, 40),
        "skills": (
            "History",
            "Language (Other)",
            "Language (Own)",
            "Listen",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "RANDOM",
        ),
    },
    "Forensic Surgeon": {
        "skill_points": "EDU×4",
        "credit_range": (40, 60),
        "skills": (
            "Language (Latin)",
            "Library Use",
            "Medicine",
            "Persuade",
            "Science (Biology)",
            "Science (Forensics)",
            "Science (Pharmacy)",
            "Spot Hidden",
        ),
    },
    "Forger/Counterfeiter": {
        "skill_points": "EDU×4",
        "credit_range": (20, 60),
        "skills": (
            "Accounting",
            "Appraise",
            "Art and Craft (Forgery)",
            "History",
            "Library Use",
            "Spot Hidden",
            "Sleight of Hand",
            "RANDOM",
        ),
    },
    "Gambler": {
        "skill_points": "EDU×2+DEX×2|EDU×2+APP×2",
        "credit_range": (8, 50),
        "skills": (
            "Accounting",
            "Art and Craft (Acting)",
            "SOCIAL",
            "SOCIAL",
            "Listen",
            "Psychology",
            "Sleight of Hand",
            "Spot Hidden",
        ),
    },
    "Gangster Underling": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Drive Auto",
            "FIGHT",
            "FIREARM",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Gangster Boss": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (60, 95),
        "skills": (
            "FIGHT",
            "FIREARM",
            "Law",
            "Listen",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "Spot Hidden",
        ),
    },
    "Gentleman/Lady": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (40, 90),
        "skills": (
            "ART",
            "SOCIAL",
            "SOCIAL",
            "Firearms (Rifle)",
            "History",
            "Language (Other)",
            "Navigate",
            "Ride",
        ),
    },
    "Hobo": {
        "skill_points": "EDU×2+DEX×2|EDU×2+APP×2",
        "credit_range": (0, 5),
        "skills": (
            "ART",
            "Climb",
            "Jump",
            "Listen",
            "Locksmith",
            "Sleight of Hand",
            "Navigate",
            "Stealth",
            "RANDOM",
        ),
    },
    "Hospital Orderly": {
        "skill_points": "EDU×2+STR×2",
        "credit_range": (6, 15),
        "skills": (
            "Electrical Repair",
            "SOCIAL",
            "Fighting (Brawl)",
            "First Aid",
            "Listen",
            "Mechanical Repair",
            "Psychology",
            "Stealth",
        ),
    },
    "Investigative Journalist": {
        "skill_points": "EDU×4",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Photography)",
            "History",
            "Library Use",
            "Language (Own)",
            "SOCIAL",
            "Psychology",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Judge": {
        "skill_points": "EDU×4",
        "credit_range": (50, 80),
        "skills": (
            "History",
            "Intimidate",
            "Law",
            "Library Use",
            "Listen",
            "Language (Own)",
            "Persuade",
            "Psychology",
        ),
    },
    "Laborer, Unskilled": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Drive Auto",
            "Electrical Repair",
            "FIGHT",
            "First Aid",
            "Mechanical Repair",
            "Operate Heavy Machinery",
            "Throw",
            "RANDOM",
        ),
    },
    "Lawyer": {
        "skill_points": "EDU×4",
        "credit_range": (30, 80),
        "skills": (
            "Accounting",
            "Law",
            "Library Use",
            "Psychology",
            "SOCIAL",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Librarian": {
        "skill_points": "EDU×4",
        "credit_range": (9, 35),
        "skills": (
            "Accounting",
            "Library Use",
            "Language (Own)",
            "Language (Other)",
            "RANDOM",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Lumberjack": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Climb",
            "Dodge",
            "Fighting (Chainsaw)",
            "First Aid",
            "Jump",
            "Mechanical Repair",
            "Natural World",
            "Science (Biology)",
            "Science (Botany)",
            "Throw",
        ),
    },
    "Mechanic": {
        "skill_points": "EDU×4",
        "credit_range": (9, 40),
        "skills": (
            "CRAFT",
            "Climb",
            "Drive Auto",
            "Electrical Repair",
            "Mechanical Repair",
            "Operate Heavy Machinery",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Military Officer": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (20, 70),
        "skills": (
            "Accounting",
            "FIREARM",
            "Navigate",
            "Psychology",
            "First Aid",
            "SOCIAL",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Miner": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (3, 30),
        "skills": (
            "Climb",
            "Science (Geology)",
            "Jump",
            "Mechanical Repair",
            "Operate Heavy Machinery",
            "Stealth",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Missionary": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (0, 30),
        "skills": (
            "First Aid",
            "Mechanical Repair",
            "Medicine",
            "Natural World",
            "ART",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Mountain Climber": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (30, 60),
        "skills": (
            "Climb",
            "First Aid",
            "Jump",
            "Listen",
            "Navigate",
            "Language (Other)",
            "Survival (Alpine)",
            "Track",
        ),
    },
    "Museum Curator": {
        "skill_points": "EDU×4",
        "credit_range": (10, 30),
        "skills": (
            "Accounting",
            "Appraise",
            "Archaeology",
            "History",
            "Library Use",
            "Occult",
            "Language (Other)",
            "Spot Hidden",
        ),
    },
    "Musician": {
        "skill_points": "EDU×2+DEX×2|EDU×2+POW×2",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Instrument)",
            "Listen",
            "Psychology",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Nurse": {
        "skill_points": "EDU×4",
        "credit_range": (9, 30),
        "skills": (
            "First Aid",
            "Listen",
            "Medicine",
            "SOCIAL",
            "Psychology",
            "Science (Biology)",
            "Science (Chemistry)",
            "Spot Hidden",
        ),
    },
    "Occultist": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            (
                "Anthropology",
                "History",
                "Library Use",
                "SOCIAL",
                "Occult",
                "Language (Other)",
                "Science (Astronomy)",
                "RANDOM",
            )
        ),
    },
    "Outdoorsman/Outdoorswoman": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (5, 20),
        "skills": (
            "FIREARM",
            "First Aid",
            "Listen",
            "Natural World",
            "Navigate",
            "Spot Hidden",
            "SURVIVE",
            "Track",
        ),
    },
    "Parapsychologist": {
        "skill_points": "EDU×4",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Photography)",
            "Anthropology",
            "History",
            "Library Use",
            "Occult",
            "Psychology",
            "Language (Other)",
            "RANDOM",
        ),
    },
    "Pharmacist": {
        "skill_points": "EDU×4",
        "credit_range": (35, 75),
        "skills": (
            "Accounting",
            "First Aid",
            "Language (Latin)",
            "Library Use",
            "SOCIAL",
            "Psychology",
            "Science (Pharmacy)",
            "Science (Chemistry)",
        ),
    },
    "Photographer": {
        "skill_points": "EDU×4",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Photography)",
            "SOCIAL",
            "Psychology",
            "Science (Chemistry)",
            "Stealth",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Photojournalist": {
        "skill_points": "EDU×4",
        "credit_range": (10, 30),
        "skills": (
            "Art and Craft (Photography)",
            "Climb",
            "SOCIAL",
            "Language (Other)",
            "Psychology",
            "Science (Chemistry)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Pilot": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (20, 70),
        "skills": (
            "Electrical Repair",
            "Mechanical Repair",
            "Navigate",
            "Operate Heavy Machinery",
            "Pilot (Aircraft)",
            "Science (Astronomy)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Police Detective": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (20, 50),
        "skills": (
            "Art and Craft (Acting)",
            "Disguise",
            "FIREARM",
            "Law",
            "Listen",
            "Psychology",
            "Spot Hidden",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Uniformed Police Officer": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Fighting (Brawl)",
            "FIREARM",
            "First Aid",
            "Law",
            "Psychology",
            "Spot Hidden",
            "Drive Auto",
            "Ride",
            "SOCIAL",
        ),
    },
    "Private Investigator": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Art and Craft (Photography)",
            "Disguise",
            "Law",
            "Library Use",
            "SOCIAL",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Professor": {
        "skill_points": "EDU×4",
        "credit_range": (20, 70),
        "skills": (
            "Library Use",
            "Language (Other)",
            "Language (Own)",
            "Psychology",
            "RANDOM",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Prospector": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (0, 10),
        "skills": (
            "Climb",
            "First Aid",
            "History",
            "Mechanical Repair",
            "Navigate",
            "Science (Geology)",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Prostitute": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (5, 50),
        "skills": (
            "ART",
            "SOCIAL",
            "SOCIAL",
            "Dodge",
            "Psychology",
            "Sleight of Hand",
            "Stealth",
            "RANDOM",
        ),
    },
    "Psychiatrist": {
        "skill_points": "EDU×4",
        "credit_range": (30, 80),
        "skills": (
            "Language (Other)",
            "Listen",
            "Medicine",
            "Persuade",
            "Psychoanalysis",
            "Psychology",
            "Science (Biology)",
            "Science (Chemistry)",
        ),
    },
    "Psychologist/Psychoanalyst": {
        "skill_points": "EDU×4",
        "credit_range": (10, 40),
        "skills": (
            "Accounting",
            "Library Use",
            "Listen",
            "Persuade",
            "Psychoanalysis",
            "Psychology",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Reporter": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Art and Craft (Acting)",
            "History",
            "Listen",
            "Language (Own)",
            "SOCIAL",
            "Psychology",
            "Stealth",
            "Spot Hidden",
        ),
    },
    "Researcher": {
        "skill_points": "EDU×4",
        "credit_range": (9, 30),
        "skills": (
            "History",
            "Library Use",
            "SOCIAL",
            "Language (Other)",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Sailor, Commercial": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (20, 40),
        "skills": (
            "First Aid",
            "Mechanical Repair",
            "Natural World",
            "Navigate",
            "SOCIAL",
            "Pilot (Boat)",
            "Spot Hidden",
            "Swim",
        ),
    },
    "Sailor, Naval": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Electrical Repair",
            "Mechanical Repair",
            "FIGHT",
            "FIREARM",
            "First Aid",
            "Navigate",
            "Pilot (Boat)",
            "Survival (Sea)",
            "Swim",
        ),
    },
    "Salesperson": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (9, 40),
        "skills": (
            "Accounting",
            "SOCIAL",
            "SOCIAL",
            "Drive Auto",
            "Listen",
            "Psychology",
            "Stealth",
            "Sleight of Hand",
            "RANDOM",
        ),
    },
    "Shopkeeper": {
        "skill_points": "EDU×2+DEX×2|EDU×2+APP×2",
        "credit_range": (20, 40),
        "skills": (
            "Accounting",
            "SOCIAL",
            "SOCIAL",
            "Electrical Repair",
            "Listen",
            "Mechanical Repair",
            "Psychology",
            "Spot Hidden",
        ),
    },
    "Smuggler": {
        "skill_points": "EDU×2+DEX×2|EDU×2+APP×2",
        "credit_range": (20, 60),
        "skills": (
            "FIREARM",
            "Listen",
            "Navigate",
            "SOCIAL",
            "Drive Auto",
            "Pilot (Aircraft)",
            "Pilot (Boat)",
            "Psychology",
            "Sleight of Hand",
            "Spot Hidden",
        ),
    },
    "Soldier": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 30),
        "skills": (
            "Climb",
            "Swim",
            "Dodge",
            "Stealth",
            "SURVIVE",
            "First Aid",
            "Mechanical Repair",
            "FIREARM",
            "FIGHT",
            "Language (Other)",
        ),
    },
    "Spy": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Art and Craft (Acting)",
            "Disguise",
            "FIREARM",
            "Listen",
            "Language (Other)",
            "SOCIAL",
            "Psychology",
            "Sleight of Hand",
            "Stealth",
        ),
    },
    "Street Punk": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            "Climb",
            "SOCIAL",
            "FIGHT",
            "FIREARM",
            "Jump",
            "Sleight of Hand",
            "Stealth",
            "Throw",
        ),
    },
    "Student/Intern": {
        "skill_points": "EDU×4",
        "credit_range": (5, 10),
        "skills": (
            "Language (Own)",
            "Language (Other)",
            "Library Use",
            "Listen",
            "RANDOM",
            "RANDOM",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Stuntman": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (10, 50),
        "skills": (
            "Climb",
            "Dodge",
            "Electrical Repair",
            "Mechanical Repair",
            "FIGHT",
            "First Aid",
            "Jump",
            "Swim",
            "Diving",
            "Drive Auto",
            "PILOT",
            "Ride",
        ),
    },
    "Taxi Driver": {
        "skill_points": "EDU×2+DEX×2",
        "credit_range": (9, 30),
        "skills": (
            "Accounting",
            "Drive Auto",
            "Electrical Repair",
            "Fast Talk",
            "Mechanical Repair",
            "Navigate",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Thug": {
        "skill_points": "EDU×2+STR×2",
        "credit_range": (5, 30),
        "skills": (
            "Drive Auto",
            "FIGHT",
            "FIREARM",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "Stealth",
            "Spot Hidden",
        ),
    },
    "Tribe Member": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (0, 15),
        "skills": (
            "Climb",
            "FIGHT",
            "Throw",
            "Natural World",
            "Listen",
            "Occult",
            "Spot Hidden",
            "Swim",
            "SURVIVE",
        ),
    },
    "Undertaker": {
        "skill_points": "EDU×4",
        "credit_range": (20, 40),
        "skills": (
            "Accounting",
            "Drive Auto",
            "SOCIAL",
            "History",
            "Occult",
            "Psychology",
            "Science (Biology)",
            "Science (Chemistry)",
        ),
    },
    "Union Activist": {
        "skill_points": "EDU×4",
        "credit_range": (5, 30),
        "skills": (
            "Accounting",
            "SOCIAL",
            "SOCIAL",
            "Fighting (Brawl)",
            "Law",
            "Listen",
            "Operate Heavy Machinery",
            "Psychology",
        ),
    },
    "Waiter": {
        "skill_points": "EDU×2+APP×2|EDU×2+DEX×2",
        "credit_range": (9, 20),
        "skills": (
            "Accounting",
            "ART",
            "Dodge",
            "Listen",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "RANDOM",
        ),
    },
    "Senior Manager": {
        "skill_points": "EDU×4",
        "credit_range": (20, 80),
        "skills": (
            "Accounting",
            "Language (Other)",
            "Law",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Zealot": {
        "skill_points": "EDU×2+APP×2|EDU×2+POW×2",
        "credit_range": (0, 30),
        "skills": (
            "History",
            "Psychology",
            "Stealth",
            "SOCIAL",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Zookeeper": {
        "skill_points": "EDU×4",
        "credit_range": (9, 40),
        "skills": (
            "Animal Handling",
            "Accounting",
            "Dodge",
            "First Aid",
            "Natural World",
            "Medicine",
            "Science (Pharmacy)",
            "Science (Zoology)",
        ),
    },
}


occupations_20s_data = {
    "Alienist": {
        "skill_points": "EDU×4",
        "credit_range": (10, 60),
        "skills": (
            "Law",
            "Listen",
            "Medicine",
            "Language (Other)",
            "Psychoanalysis",
            "Psychology",
            "Science (Biology)",
            "Science (Chemistry)",
        ),
    },
    "Aviator": {
        "skill_points": "EDU×4",
        "credit_range": (30, 60),
        "skills": (
            "Accounting",
            "Electrical Repair",
            "Listen",
            "Mechanical Repair",
            "Navigate",
            "Pilot (Aircraft)",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Explorer": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2|EDU×2+APP×2",
        "credit_range": (55, 80),
        "skills": (
            "Climb",
            "Swim",
            "FIREARM",
            "History",
            "Jump",
            "Natural World",
            "Navigate",
            "Language (Other)",
            "Survival",
        ),
    },
    "Gun Moll": {
        "skill_points": "EDU×2+APP×2",
        "credit_range": (10, 80),
        "skills": (
            "ART",
            "SOCIAL",
            "SOCIAL",
            "Fighting (Brawl)",
            "Firearms (Handgun)",
            "Drive Auto",
            "Listen",
            "Stealth",
            "RANDOM",
        ),
    },
    "Architect": {
        "skill_points": "EDU×4",
        "credit_range": (30, 70),
        "skills": (
            "RANDOM",
            "Accounting",
            "Art and Craft (Technical Drawing)",
            "Law",
            "Language (Own)",
            "Library Use",
            "Persuade",
            "Psychology",
            "Science (Mathematics)",
        ),
    },
    "Designer": {
        "skill_points": "EDU×4",
        "credit_range": (20, 60),
        "skills": (
            "Accounting",
            "Art and Craft (Photography)",
            "ART",
            "Library Use",
            "Mechanical Repair",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Laboratory Assistant": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            (
                "Library Use",
                "Electrical Repair",
                "Language (Other)",
                "Science (Chemistry)",
                "SCIENCE",
                "SCIENCE",
                "Spot Hidden",
                "RANDOM",
            )
        ),
    },
    "Scientist": {
        "skill_points": "EDU×4",
        "credit_range": (9, 50),
        "skills": (
            "Library Use",
            "Language (Other)",
            "Language (Own)",
            "SOCIAL",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Secretary": {
        "skill_points": "EDU×2+DEX×2|EDU×2+APP×2",
        "credit_range": (9, 30),
        "skills": (
            "Accounting",
            "Art and Craft (Typing)",
            "Art and Craft (Short Hand)",
            "SOCIAL",
            "SOCIAL",
            "Language (Own)",
            "Library Use",
            "Psychology",
            "RANDOM",
        ),
    },
    "Clerk": {
        "skill_points": "EDU×4",
        "credit_range": (9, 20),
        "skills": (
            "Accounting",
            "Language (Own)",
            "Language (Other)",
            "Law",
            "Library Use",
            "Listen",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
}

occupations_20s_data.update(occupations_base)

occupations_modern_data = {
    "Hacker": {
        "skill_points": "EDU×4",
        "credit_range": (10, 70),
        "skills": (
            "Computer Use",
            "Electrical Repair",
            "Electronics",
            "Library Use",
            "Spot Hidden",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Computer Programmer/Technician": {
        "skill_points": "EDU×4",
        "credit_range": (10, 70),
        "skills": (
            "Computer Use",
            "Electrical Repair",
            "Electronics",
            "Library Use",
            "Science (Mathematics)",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Software Tester": {
        "skill_points": "EDU×4",
        "credit_range": (20, 60),
        "skills": (
            "Computer Use",
            "Fighting (Brawl)",
            "FIREARM",
            "Listen",
            "SOCIAL",
            "SOCIAL",
            "Psychology",
            "Spot Hidden",
        ),
    },
    "Deprogrammer": {
        "skill_points": "EDU×4",
        "credit_range": (20, 50),
        "skills": (
            "SOCIAL",
            "SOCIAL",
            "Drive Auto",
            "Fighting (Brawl)",
            "FIREARM",
            "History",
            "Occult",
            "Psychology",
            "Stealth",
        ),
    },
    "Architect": {
        "skill_points": "EDU×4",
        "credit_range": (30, 70),
        "skills": (
            "RANDOM",
            "Accounting",
            "Art and Craft (Technical Drawing)",
            "Law",
            "Language (Own)",
            "Computer Use",
            "Library Use",
            "Persuade",
            "Psychology",
            "Science (Mathematics)",
        ),
    },
    "Designer": {
        "skill_points": "EDU×4",
        "credit_range": (20, 60),
        "skills": (
            "Accounting",
            "Art and Craft (Photography)",
            "ART",
            "Computer Use",
            "Library Use",
            "Mechanical Repair",
            "Psychology",
            "Spot Hidden",
            "RANDOM",
        ),
    },
    "Laboratory Assistant": {
        "skill_points": "EDU×2+DEX×2|EDU×2+STR×2",
        "credit_range": (9, 70),
        "skills": (
            (
                "Computer Use",
                "Library Use",
                "Electrical Repair",
                "Language (Other)",
                "Science (Chemistry)",
                "SCIENCE",
                "SCIENCE",
                "Spot Hidden",
                "RANDOM",
            )
        ),
    },
    "Scientist": {
        "skill_points": "EDU×4",
        "credit_range": (9, 50),
        "skills": (
            "Computer Use",
            "Library Use",
            "Language (Other)",
            "Language (Own)",
            "SOCIAL",
            "Spot Hidden",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Secretary": {
        "skill_points": "EDU×2+DEX×2|EDU×2+APP×2",
        "credit_range": (9, 30),
        "skills": (
            "Accounting",
            "Art and Craft (Typing)",
            "Art and Craft (Short Hand)",
            "SOCIAL",
            "SOCIAL",
            "Language (Own)",
            "Library Use",
            "Computer Use",
            "Psychology",
            "RANDOM",
        ),
    },
    "Clerk": {
        "skill_points": "EDU×4",
        "credit_range": (9, 20),
        "skills": (
            "Accounting",
            "Language (Own)",
            "Language (Other)",
            "Law",
            "Library Use",
            "Computer Use",
            "Listen",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
}
