"""Lists all skills and their base values."""

from coc_gen.base_classes import Skill

skills_20s = {}
skills_modern = {}

for s in (
    Skill("Accounting", "5%"),
    Skill("Anthropology", "1%"),
    Skill("Appraise", "5%"),
    Skill("Archaeology", "1%"),
    Skill("Animal Handling", "5%"),
    Skill("Art and Craft (Acting)", "5%"),
    Skill("Art and Craft (Carpentry)", "5%"),
    Skill("Art and Craft (Welding)", "5%"),
    Skill("Art and Craft (Plumbing)", "5%"),
    Skill("Art and Craft (Farming)", "5%"),
    Skill("Art and Craft (Fine Art)", "5%"),
    Skill("Art and Craft (Forgery)", "1%"),
    Skill("Art and Craft (Instrument)", "5%"),
    Skill("Art and Craft (Singing)", "5%"),
    Skill("Art and Craft (Literature)", "5%"),
    Skill("Art and Craft (Photography)", "5%"),
    Skill("Art and Craft (Typing)", "5%"),
    Skill("Art and Craft (Short Hand)", "5%"),
    Skill("Art and Craft (Technical Drawing)", "5%"),
    Skill("Charm", "15%"),
    Skill("Climb", "20%"),
    Skill("Credit Rating", "0%"),
    Skill("Cthulhu Mythos", "0%"),
    Skill("Disguise", "5%"),
    Skill("Diving", "1%"),
    Skill("Dodge", "DEX/2"),
    Skill("Drive Auto", "20%"),
    Skill("Electrical Repair", "10%"),
    Skill("Fast Talk", "5%"),
    Skill("Fighting (Axe)", "15%"),
    Skill("Fighting (Brawl)", "25%"),
    Skill("Fighting (Chainsaw)", "10%"),
    Skill("Fighting (Flail)", "10%"),
    Skill("Fighting (Garrote)", "15%"),
    Skill("Fighting (Spear)", "20%"),
    Skill("Fighting (Sword)", "20%"),
    Skill("Fighting (Whip)", "5%"),
    Skill("Firearms (Bow)", "15%"),
    Skill("Firearms (Flamethrower)", "10%"),
    Skill("Firearms (Handgun)", "20%"),
    Skill("Firearms (Heavy Weapons)", "10%"),
    Skill("Firearms (Machine Gun)", "10%"),
    Skill("Firearms (Rifle)", "25%"),
    Skill("Firearms (Shotgun)", "25%"),
    Skill("Firearms (Submachine Gun)", "15%"),
    Skill("First Aid", "30%"),
    Skill("History", "5%"),
    Skill("Intimidate", "15%"),
    Skill("Jump", "20%"),
    Skill("Language (Latin)", "1%"),
    Skill("Language (Other)", "1%"),
    Skill("Language (Own)", "EDU"),
    Skill("Law", "5%"),
    Skill("Library Use", "20%"),
    Skill("Listen", "20%"),
    Skill("Locksmith", "1%"),
    Skill("Mechanical Repair", "10%"),
    Skill("Medicine", "1%"),
    Skill("Natural World", "10%"),
    Skill("Navigate", "10%"),
    Skill("Occult", "5%"),
    Skill("Operate Heavy Machinery", "1%"),
    Skill("Persuade", "10%"),
    Skill("Pilot (Aircraft)", "1%"),
    Skill("Pilot (Boat)", "1%"),
    Skill("Pilot", "1%"),
    Skill("Psychoanalysis", "1%"),
    Skill("Psychology", "10%"),
    Skill("Ride", "5%"),
    Skill("Science (Astronomy)", "1%"),
    Skill("Science (Biology)", "1%"),
    Skill("Science (Botany)", "1%"),
    Skill("Science (Chemistry)", "1%"),
    Skill("Science (Cryptography)", "1%"),
    Skill("Science (Engineering)", "1%"),
    Skill("Science (Forensics)", "5%"),
    Skill("Science (Geology)", "1%"),
    Skill("Science (Mathematics)", "10%"),
    Skill("Science (Meteorology)", "1%"),
    Skill("Science (Pharmacy)", "1%"),
    Skill("Science (Physics)", "1%"),
    Skill("Science (Zoology)", "1%"),
    Skill("Sleight of Hand", "10%"),
    Skill("Spot Hidden", "25%"),
    Skill("Stealth", "20%"),
    Skill("Survival (Sea)", "10%"),
    Skill("Survival (Alpine)", "10%"),
    Skill("Survival", "10%"),
    Skill("Swim", "20%"),
    Skill("Throw", "20%"),
    Skill("Track", "10%"),
):
    skills_20s[s.name] = s
    skills_modern[s.name] = s


for s in ():
    skills_20s[s.name] = s

for s in (
    Skill("Computer Use", "5%"),
    Skill("Electronics", "1%"),
):
    skills_modern[s.name] = s
