"""A list of occupations for Call ­Cthulhu Sverige."""

occupations_data = {
    "Agitator": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (8, 25),
        "skills": (
            "Bibliotekskunskap",
            "Charma",
            "Bluffa",
            "Konst & hantverk (Skådespelare)",
            "Psykologi",
            "Språk (Annat)",
            "Övertyga",
            "RANDOM",
        ),
    },
    "Antikhandlare": {
        "skill_points": "UTB×4",
        "credit_range": (30, 50),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Historia",
            "Språk (Annat)",
            "Språk (Annat)",
            "Värdering",
            "SOCIAL",
            "SOCIAL",
        ),
    },
    "Arbetare": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (8, 30),
        "skills": (
            "Finna dolda ting",
            "Klättra",
            "Lyssna",
            "Strid (Handgemäng)",
            "WORKER",
            "WORKER",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Arkeolog": {
        "skill_points": "UTB×4",
        "credit_range": (10, 40),
        "skills": (
            "Arkeologi",
            "Bibliotekskunskap",
            "Historia",
            "Mekaniker",
            "Navigera",
            "Språk (Annat)",
            "Vetenskap (Fysik)",
            "Vetenskap (Geologi)",
            "Vetenskap (Kemi)",
            "Värdering",
        ),
    },
    "Arkitekt": {
        "skill_points": "UTB×4",
        "credit_range": (30, 70),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Konst & hantverk (Tekniska Ritningar)",
            "Juridik",
            "Psykologi",
            "Språk (Annat)",
            "Vetenskap (Matematik)",
            "Övertyga",
        ),
    },
    "Bedragare": {
        "skill_points": "UTB×4",
        "credit_range": (9, 60),
        "skills": (
            "Bibliotekskunskap",
            "Bluffa",
            "Bokföring",
            "Charma",
            "Juridik",
            "Konst & hantverk (Förfalskning)",
            "Språk (Annat)",
            "Värdering",
        ),
    },
    "Betjänt-Hembiträde": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (9, 35),
        "skills": (
            "Bokföring",
            "Värdering",
            "Finna dolda ting",
            "Första hjälpen",
            "Konst & hantverk (Barberare)",
            "Konst & hantverk (Matlagning)",
            "Konst & hantverk (Sömnad)",
            "Språk (Annat)",
            "Psykologi",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Bibliotekarie": {
        "skill_points": "UTB×4",
        "credit_range": (9, 35),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Språk (Annat)",
            "Språk (Eget)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Bokhållare": {
        "skill_points": "UTB×4",
        "credit_range": (30, 60),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Finna dolda ting",
            "Juridik",
            "Lyssna",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Brandsoldat": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (10, 25),
        "skills": (
            "Chaufför (Bil)",
            "Första hjälpen",
            "Hoppa",
            "Kasta",
            "Klättra",
            "Simma",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Bartender-Krögare": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (8, 30),
        "skills": (
            "Bokföring",
            "Finna dolda ting",
            "Konst & hantverk (Matlagning)",
            "Lyssna",
            "Psykologi",
            "Strid (Handgemäng)",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Bokhandlare": {
        "skill_points": "UTB×4",
        "credit_range": (20, 40),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Chaufför (Bil)",
            "Historia",
            "Språk (Annat)",
            "Språk (Eget)",
            "Värdering",
            "RANDOM",
        ),
    },
    "Chaufför": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (8, 20),
        "skills": (
            "Chaufför (Bil)",
            "Chaufför (Droska)",
            "Chaufför (Lastbil)",
            "Chaufför (Motorcykel)",
            "Chaufför (Traktor)",
            "Elektriker",
            "Finna dolda ting",
            "Maskinist",
            "Mekaniker",
            "Navigera",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Cirkusartist": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (8, 20),
        "skills": (
            "Finna dolda ting",
            "Hoppa",
            "Ducka",
            "Kasta",
            "Klättra",
            "Simma",
            "Konst & hantverk (Skådespelare)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Daglönare": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (0, 10),
        "skills": (
            "Chaufför (Bil)",
            "Chaufför (Lastbil)",
            "Hoppa",
            "Klättra",
            "Mekaniker",
            "Konst & hantverk (Sprängteknik)",
            "Strid (Handgemäng)",
            "Bluffa",
            "Hota",
            "RANDOM",
        ),
    },
    "Dräng-Piga-Statare": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (1, 9),
        "skills": (
            "Chaufför (Droska)",
            "Konst & hantverk (Dressyr)",
            "Hoppa",
            "Klättra",
            "Naturkunskap",
            "Smyga",
            "Spåra",
            "RANDOM",
        ),
    },
    "Dykare": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (8, 30),
        "skills": (
            "Dyka",
            "Första hjälpen",
            "Mekaniker",
            "Klättra",
            "Simma",
            "Konst & hantverk (Sprängteknik)",
            "Skeppare",
            "RANDOM",
        ),
    },
    "Estradör": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (21, 60),
        "skills": (
            "Bluffa",
            "Bokföring",
            "Charma",
            "Konst & hantverk (Skådespelare)",
            "Språk (Annat)",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Fabrikör": {
        "skill_points": "UTB×4",
        "credit_range": (40, 90),
        "skills": (
            "Bokföring",
            "Juridik",
            "Psykologi",
            "Språk (Annat)",
            "SCIENCE",
            "RANDOM",
            "SOCIAL",
            "SOCIAL",
        ),
    },
    "Fotograf": {
        "skill_points": "UTB×4",
        "credit_range": (9, 30),
        "skills": (
            "Charma",
            "Konst & hantverk (Fotografi)",
            "ART",
            "Mekaniker",
            "Språk (Annat)",
            "Vetenskap (Kemi)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Författare": {
        "skill_points": "UTB×4",
        "credit_range": (9, 40),
        "skills": (
            "Bibliotekskunskap",
            "Historia",
            "Konst & hantverk (Författare)",
            "Naturkunskap",
            "Ockultism",
            "Psykologi",
            "Språk (Annat)",
            "Språk (Eget)",
            "RANDOM",
        ),
    },
    "Idrottare": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (9, 30),
        "skills": (
            "Hoppa",
            "Kasta",
            "Klättra",
            "Rida",
            "Simma",
            "Strid (Handgemäng)",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Ingenjör": {
        "skill_points": "UTB×4",
        "credit_range": (30, 90),
        "skills": (
            "Bibliotekskunskap",
            "Elektriker",
            "Mekaniker",
            "Språk (Annat)",
            "Vetenskap (Matematik)",
            "Vetenskap (Ingenjörskonst)",
            "SCIENCE",
            "RANDOM",
        ),
    },
    "Journalist": {
        "skill_points": "UTB×4",
        "credit_range": (9, 40),
        "skills": (
            "Bibliotekskunskap",
            "Historia",
            "Konst & hantverk (Författare)",
            "Psykologi",
            "Språk (Annat)",
            "Språk (Eget)",
            "Övertyga",
            "RANDOM",
        ),
    },
    "Jurist": {
        "skill_points": "UTB×4",
        "credit_range": (40, 90),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Historia",
            "Juridik",
            "Språk (Annat)",
            "Språk (Eget)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Konstkännare": {
        "skill_points": "UTB×4",
        "credit_range": (30, 70),
        "skills": (
            "Bibliotekskunskap",
            "Finna dolda ting",
            "ART",
            "Språk (Annat)",
            "Språk (Annat)",
            "Värdering",
            "RANDOM",
        ),
    },
    "Konstnär": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (9, 50),
        "skills": (
            "Finna dolda ting",
            "Historia",
            "Naturkunskap",
            "ART",
            "Psykologi",
            "Språk (Annat)",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Landsfiskal": {
        "skill_points": "UTB×4",
        "credit_range": (20, 50),
        "skills": (
            "Bokföring",
            "Finna dolda ting",
            "Juridik",
            "Vetenskap (Kriminalteknik)",
            "Skjutvapen (Pistol)",
            "Strid (Handgemäng)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Lantbrukare": {
        "skill_points": "UTB×4",
        "credit_range": (20, 70),
        "skills": (
            "Bokföring",
            "Finna dolda ting",
            "Juridik",
            "Vetenskap (Kriminalteknik)",
            "Skjutvapen (Pistol)",
            "Strid (Handgemäng)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Ligist": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (0, 8),
        "skills": (
            "Fingerfärdighet",
            "Hoppa",
            "Hota",
            "Kasta",
            "Klättra",
            "Lyssna",
            "Smyga",
            "Strid (Handgemäng)",
        ),
    },
    "Luffare": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (0, 8),
        "skills": (
            "Finna dolda ting",
            "Klättra",
            "Lyssna",
            "Naturkunskap",
            "Smyga",
            "Språk (Luffarjargong)",
            "SURVIVAL",
            "RANDOM",
        ),
    },
    "Läkare": {
        "skill_points": "UTB×4",
        "credit_range": (4, 90),
        "skills": (
            "Bibliotekskunskap",
            "Första hjälpen",
            "Läkekonst",
            "Språk (Annat)",
            "Vetenskap (Biologi)",
            "Vetenskap (Läkemedel)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Mekaniker": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (8, 30),
        "skills": (
            "Bokföring",
            "DRIVER",
            "Elektriker",
            "Maskinist",
            "Mekaniker",
            "Värdering",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Mentalvårdare": {
        "skill_points": "UTB×4+STY×2",
        "credit_range": (10, 40),
        "skills": (
            "Finna dolda ting",
            "Första hjälpen",
            "Hota",
            "Lyssna",
            "Strid (Handgemäng)",
            "Psykologi",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Missionär": {
        "skill_points": "UTB×4",
        "credit_range": (10, 30),
        "skills": (
            "Bibliotekskunskap",
            "Första hjälpen",
            "Konst & hantverk (Författare)",
            "Språk (Annat)",
            "Psykologi",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Musiker": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (9, 30),
        "skills": (
            "Konst & hantverk (Valfritt Instrument)",
            "Lyssna",
            "Psykologi",
            "SOCIAL",
            "RANDOM",
            "RANDOM",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Nåjd": {
        "skill_points": "UTB×2+VST×2",
        "credit_range": (5, 15),
        "skills": (
            "ART",
            "Naturkunskap",
            "Ockultism",
            "Smyga",
            "Spåra",
            "Språk (Svenska)",
            "Överlevnad (Arktis)",
            "RANDOM",
        ),
    },
    "Officer": {
        "skill_points": "UTB×4",
        "credit_range": (20, 70),
        "skills": (
            "Ducka",
            "Första hjälpen",
            "Psykologi",
            "Rida",
            "COMBAT",
            "GUN",
            "Övertyga",
            "RANDOM",
        ),
    },
    "Pilot": {
        "skill_points": "UTB×4",
        "credit_range": (15, 40),
        "skills": (
            "Elektriker",
            "Mekaniker",
            "Navigera",
            "Pilot",
            "Språk (Annat)",
            "Vetenskap (Meteorologi)",
            "RANDOM",
        ),
    },
    "Polisdetektiv": {
        "skill_points": "UTB×4",
        "credit_range": (20, 40),
        "skills": (
            "Bibliotekskunskap",
            "Bluffa",
            "Finna dolda ting",
            "Vetenskap (Kriminalteknik)",
            "Psykologi",
            "Skjutvapen (Pistol)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Poliskonstapel": {
        "skill_points": "UTB×4",
        "credit_range": (10, 30),
        "skills": (
            "Chaufför (Bil)",
            "Finna dolda ting",
            "Vetenskap (Kriminalteknik)",
            "Skjutvapen (Pistol)",
            "Strid (Handgemäng)",
            "Strid (Sabel)",
            "Psykologi",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Polissyster": {
        "skill_points": "UTB×4",
        "credit_range": (10, 30),
        "skills": (
            "Bokföring",
            "Charma",
            "Finna dolda ting",
            "Första hjälpen",
            "Vetenskap (Kriminalteknik)",
            "Psykologi",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Präst": {
        "skill_points": "UTB×4",
        "credit_range": (9, 60),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Historia",
            "Lyssna",
            "Psykologi",
            "Språk (Annat)",
            "Övertyga",
            "RANDOM",
        ),
    },
    "Psykolog": {
        "skill_points": "UTB×4",
        "credit_range": (10, 40),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Lyssna",
            "Psykoanalys",
            "Psykologi",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Redaktör-Förläggare": {
        "skill_points": "UTB×4",
        "credit_range": (25, 60),
        "skills": (
            "Bibliotekskunskap",
            "Bokföring",
            "Historia",
            "Konst & hantverk (Författare)",
            "Psykologi",
            "Språk (Annat)",
            "Övertyga",
            "RANDOM",
        ),
    },
    "Renskötare": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (5, 15),
        "skills": (
            "Kasta",
            "ART",
            "Naturkunskap",
            "Språk (Svenska)",
            "Spåra",
            "Värdering",
            "Överlevnad (Arktis)",
            "RANDOM",
        ),
    },
    "Revolutionär": {
        "skill_points": "UTB×4",
        "credit_range": (9, 20),
        "skills": (
            "Bibliotekskunskap",
            "Bluffa",
            "Förklädnad",
            "Historia",
            "Hota",
            "Skjutvapen (Pistol)",
            "Övertyga",
            "RANDOM",
        ),
    },
    "Samisk jägare": {
        "skill_points": "UTB×2+FYS×2",
        "credit_range": (5, 15),
        "skills": (
            "ART",
            "Naturkunskap",
            "Skjutvapen (Gevär)",
            "Smyga",
            "Spåra",
            "Språk (Svenska)",
            "Överlevnad (Arktis)",
            "RANDOM",
        ),
    },
    "Sekreterare": {
        "skill_points": "UTB×4",
        "credit_range": (9, 20),
        "skills": (
            "Bibliotekskunskap",
            "Finna dolda ting",
            "Lyssna",
            "Psykologi",
            "Språk (Annat)",
            "Språk (Eget)",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Sjuksköterska": {
        "skill_points": "UTB×4",
        "credit_range": (10, 40),
        "skills": (
            "Bibliotekskunskap",
            "Första hjälpen",
            "Läkekonst",
            "Psykologi",
            "Språk (Annat)",
            "Vetenskap (Läkemedel)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Sjöman": {
        "skill_points": "UTB×2+SMI×2",
        "credit_range": (9, 20),
        "skills": (
            "Hoppa",
            "Kasta",
            "Klättra",
            "Navigera",
            "Simma",
            "Skeppare",
            "Språk (Annat)",
            "RANDOM",
        ),
    },
    "Teaterskådespelare": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (9, 40),
        "skills": (
            "Förklädnad",
            "Historia",
            "Konst & hantverk (Skådespelare)",
            "Psykologi",
            "Strid (Handgemäng)",
            "SOCIAL",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Filmskådespelare": {
        "skill_points": "UTB×2+KAR×2",
        "credit_range": (15, 80),
        "skills": (
            "Chaufför (Bil)",
            "Förklädnad",
            "Konst & hantverk (Skådespelare)",
            "Psykologi",
            "Strid (Handgemäng)",
            "SOCIAL",
            "SOCIAL",
            "RANDOM",
        ),
    },
    "Soldat": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (5, 15),
        "skills": (
            "Chaufför (Droska)",
            "Ducka",
            "Hoppa",
            "Klättra",
            "GUN",
            "GUN",
            "Smyga",
            "RANDOM",
        ),
    },
    "Spiritist": {
        "skill_points": "UTB×4",
        "credit_range": (10, 45),
        "skills": (
            "Bluffa",
            "Charma",
            "Fingerfärdighet",
            "Ockultism",
            "Konst & hantverk (Skådespelare)",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Spritsmugglare": {
        "skill_points": "UTB×4",
        "credit_range": (15, 60),
        "skills": (
            "Charma",
            "Mekaniker",
            "Navigera",
            "Simma",
            "Skeppare",
            "Språk (Annat)",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Student": {
        "skill_points": "UTB×4",
        "credit_range": (8, 40),
        "skills": (
            "Bibliotekskunskap",
            "Konst & hantverk (Författare)",
            "Språk (Annat)",
            "Språk (Annat 2)",
            "SCIENCE",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Universitetslärare": {
        "skill_points": "UTB×4",
        "credit_range": (20, 80),
        "skills": (
            "Bibliotekskunskap",
            "Konst & hantverk (Författare)",
            "Språk (Annat)",
            "Språk (Annat 2)",
            "SCIENCE",
            "Övertyga",
            "RANDOM",
            "RANDOM",
        ),
    },
    "Upptäcktsresande": {
        "skill_points": "UTB×2+STY×2",
        "credit_range": (10, 50),
        "skills": (
            "Bibliotekskunskap",
            "Finna dolda ting",
            "Navigera",
            "Skjutvapen (Gevär)",
            "Språk (Annat)",
            "SCIENCE",
            "SURVIVAL",
            "RANDOM",
        ),
    },
}
