"""Lists all skills and their base values."""

from coc_gen.base_classes import Skill

skills = {}

for s in (
    Skill("Antropologi", "1%"),
    Skill("Arkeologi", "1%"),
    Skill("Bibliotekskunskap", "20%"),
    Skill("Bluffa", "5%"),
    Skill("Bokföring", "5%"),
    Skill("Charma", "15%"),
    Skill("Chaufför (Bil)", "20%"),
    Skill("Chaufför (Droska)", "20%"),
    Skill("Chaufför (Lastbil)", "5%"),
    Skill("Chaufför (Motorcykel)", "5%"),
    Skill("Chaufför (Traktor)", "5%"),
    Skill("Cthulhumyten", "0%"),
    Skill("Ducka", "SMI/2"),
    Skill("Dyka", "1%"),
    Skill("Elektriker", "10%"),
    Skill("Fingerfärdighet", "10%"),
    Skill("Finna dolda ting", "25%"),
    Skill("Förklädnad", "5%"),
    Skill("Första hjälpen", "30%"),
    Skill("Historia", "5%"),
    Skill("Hoppa", "20%"),
    Skill("Hota", "15%"),
    Skill("Juridik", "5%"),
    Skill("Kasta", "20%"),
    Skill("Klättra", "20%"),
    Skill("Konst & hantverk (Barberare)", "5%"),
    Skill("Konst & hantverk (Dressyr)", "5%"),
    Skill("Konst & hantverk (Fotografi)", "5%"),
    Skill("Konst & hantverk (Förfalskning)", "5%"),
    Skill("Konst & hantverk (Författare)", "5%"),
    Skill("Konst & hantverk (Gruvarbete)", "5%"),
    Skill("Konst & hantverk (Matlagning)", "5%"),
    Skill("Konst & hantverk (Murare)", "5%"),
    Skill("Konst & hantverk (Målare)", "5%"),
    Skill("Konst & hantverk (Skogshuggare)", "5%"),
    Skill("Konst & hantverk (Skådespelare)", "5%"),
    Skill("Konst & hantverk (Snickare)", "5%"),
    Skill("Konst & hantverk (Sprängteknik)", "5%"),
    Skill("Konst & hantverk (Sömnad)", "5%"),
    Skill("Konst & hantverk (Tekniska Ritningar)", "5%"),
    Skill("Konst & hantverk (Valfritt Instrument)", "5%"),
    Skill("Levnadsstandard", "0%"),
    Skill("Lyssna", "20%"),
    Skill("Låssmed", "1%"),
    Skill("Läkekonst", "1%"),
    Skill("Läkemedel", "10%"),
    Skill("Maskinist", "1%"),
    Skill("Mekaniker", "10%"),
    Skill("Naturkunskap", "10%"),
    Skill("Navigera", "10%"),
    Skill("Ockultism", "5%"),
    Skill("Pilot - Propellerplan", "1%"),
    Skill("Pilot", "1%"),
    Skill("Psykoanalys", "1%"),
    Skill("Psykologi", "10%"),
    Skill("Rida", "5%"),
    Skill("Simma", "20%"),
    Skill("Skeppare", "1%"),
    Skill("Skjutvapen (Gevär)", "25%"),
    Skill("Skjutvapen (K-pist)", "15%"),
    Skill("Skjutvapen (Kulspruta)", "10%"),
    Skill("Skjutvapen (Pilbåge)", "15%"),
    Skill("Skjutvapen (Pistol)", "20%"),
    Skill("Skjutvapen (Spjut)", "20%"),
    Skill("Skjutvapen (Tyngre handeldvapen)", "10%"),
    Skill("Smyga", "20%"),
    Skill("Språk (Annat)", "1%"),
    Skill("Språk (Annat 2)", "1%"),
    Skill("Språk (Svenska)", "1%"),
    Skill("Språk (Eget)", "INT"),
    Skill("Språk (Luffarjargong)", "1%"),
    Skill("Spåra", "10%"),
    Skill("Strid (Eldkastare)", "10%"),
    Skill("Strid (Garott)", "15%"),
    Skill("Strid (Handgemäng)", "25%"),
    Skill("Strid (Piska)", "5%"),
    Skill("Strid (Slaga)", "10%"),
    Skill("Strid (Svärd)", "20%"),
    Skill("Strid (Sabel)", "20%"),
    Skill("Strid (Yxa)", "15%"),
    Skill("Vetenskap (Astronomi)", "1%"),
    Skill("Vetenskap (Biologi)", "1%"),
    Skill("Vetenskap (Botanik)", "1%"),
    Skill("Vetenskap (Fysik)", "1%"),
    Skill("Vetenskap (Geologi)", "1%"),
    Skill("Vetenskap (Ingenjörskonst)", "1%"),
    Skill("Vetenskap (Kemi)", "1%"),
    Skill("Vetenskap (Kriminalteknik)", "1%"),
    Skill("Vetenskap (Kryptografi)", "1%"),
    Skill("Vetenskap (Läkemedel)", "1%"),
    Skill("Vetenskap (Matematik)", "10%"),
    Skill("Vetenskap (Meteorologi)", "1%"),
    Skill("Vetenskap (Zoologi)", "1%"),
    Skill("Värdering", "5%"),
    Skill("Överlevnad (Arktis)", "10%"),
    Skill("Överlevnad (Berg)", "10%"),
    Skill("Överlevnad (Hav)", "10%"),
    Skill("Överlevnad (Regnskog)", "10%"),
    Skill("Överlevnad (Skog)", "10%"),
    Skill("Överlevnad (Stäpp)", "10%"),
    Skill("Överlevnad (Taiga)", "10%"),
    Skill("Överlevnad (Öken)", "10%"),
    Skill("Övertyga", "10%"),
):
    skills[s.name] = s
